steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - |
        docker build -t europe-west9-docker.pkg.dev/efrei-project-devops/efrei-devops/t3-app:$COMMIT_SHA --build-arg DATABASE_URL=$$DATABASE_URL --build-arg DISCORD_CLIENT_ID=$$DISCORD_CLIENT_ID --build-arg DISCORD_CLIENT_SECRET=$$DISCORD_CLIENT_SECRET --build-arg NEXTAUTH_SECRET=$$NEXTAUTH_SECRET --build-arg NEXTAUTH_URL=http://34.163.60.46 .

    secretEnv:
      [
        "DATABASE_URL",
        "DISCORD_CLIENT_ID",
        "DISCORD_CLIENT_SECRET",
        "NEXTAUTH_SECRET",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west9-docker.pkg.dev/efrei-project-devops/efrei-devops/t3-app:$COMMIT_SHA",
      ]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kubernetes.yml
      - --image=europe-west9-docker.pkg.dev/efrei-project-devops/efrei-devops/t3-app:$COMMIT_SHA
      - --location=europe-west9
      - --cluster=k8s-cluster

availableSecrets:
  secretManager:
    - versionName: projects/efrei-project-devops/secrets/DATABASE_URL/versions/latest
      env: "DATABASE_URL"
    - versionName: projects/efrei-project-devops/secrets/DISCORD_CLIENT_ID/versions/latest
      env: "DISCORD_CLIENT_ID"
    - versionName: projects/efrei-project-devops/secrets/DISCORD_CLIENT_SECRET/versions/latest
      env: "DISCORD_CLIENT_SECRET"
    - versionName: projects/efrei-project-devops/secrets/NEXTAUTH_SECRET/versions/latest
      env: "NEXTAUTH_SECRET"
images:
  - europe-west9-docker.pkg.dev/efrei-project-devops/efrei-devops/t3-app:$COMMIT_SHA
