steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west9-docker.pkg.dev/efrei-project-devops/efrei-devops/t3-app",
        ".",
        "--build-arg DATABASE_URL=$$DATABASE_URL",
        "--build-arg DISCORD_CLIENT_ID=$$DISCORD_CLIENT_ID",
        "--build-arg DISCORD_CLIENT_SECRET=$$DISCORD_CLIENT_SECRET",
        "--build-arg NEXTAUTH_SECRET=$$NEXTAUTH_SECRET",
      ]
    secretEnv:
      [
        "DATABASE_URL",
        "DISCORD_CLIENT_ID",
        "DISCORD_CLIENT_SECRET",
        "NEXTAUTH_SECRET",
      ]

availableSecrets:
  secretManager:
    - versionName: projects/efrei-project-devops/secrets/DATABASE_URL/versions/latest
      env: "DATABASE_URL"
    - versionName: projects/efrei-project-devops/secrets/DISCORD_CLIENT_ID/versions/latest
      env: "DISCORD_CLIENT_ID"
    - versionName: projects/efrei-project-devops/secrets/DISCORD_CLIENT_SECRET/versions/latest
      env: "DISCORD_CLIENT_SECRET"
    - versionName: projects/efrei-project-devops/secrets/NEXTAUTH_SECRET/versions/latest
      env: "NEXTAUTH_SECRET"
images:
  - europe-west9-docker.pkg.dev/efrei-project-devops/efrei-devops/t3-app
