apiVersion: apps/v1
kind: Deployment
metadata:
  name: t3-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      t3-app: web
  template:
    metadata:
      labels:
        t3-app: web
    spec:
      containers:
        - name: t3-app
          imagePullPolicy: Always
          image: europe-west9-docker.pkg.dev/efrei-project-devops/efrei-devops/t3-app
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: t3-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    t3-app: web
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: t3-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: t3-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
